<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Philippe Marchand, Université du Québec en Abitibi-Témiscamingue" />


<title>Statistiques spatiales en écologie, Partie 2</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>
<link href="libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Statistiques spatiales en écologie, Partie 2</h1>
<h4 class="author">Philippe Marchand, Université du Québec en Abitibi-Témiscamingue</h4>
<h4 class="date">14 janvier 2021</h4>

</div>


<div id="corrélation-spatiale-dune-variable" class="section level1">
<h1>Corrélation spatiale d’une variable</h1>
<p>La corrélation entre les mesures d’une variable prises à des points rapprochés est une caractéristique dans de nombreux jeux de données. Ce principe est parfois appelé “première loi de la géographie” et exprimé par la citation de Waldo Tobler: “Everything is related to everything else, but near things are more related than distant things.” (Tout est relié, mais les choses rapprochées le sont davantage que celles éloignées).</p>
<p>En statistique, nous parlons souvent d’<em>autocorrélation</em> pour désigner la corrélation qui existe entre les mesures d’une même variable prises à différents moments (autocorrélation temporelle) ou différents lieux (autocorrélation spatiale).</p>
<div id="dépendance-intrinsèque-ou-induite" class="section level2">
<h2>Dépendance intrinsèque ou induite</h2>
<p>Il existe deux types fondamentaux de dépendance spatiale sur une variable mesurée <span class="math inline">\(y\)</span>: une dépendance <em>intrinsèque</em> à <span class="math inline">\(y\)</span>, ou une dépendance <em>induite</em> par des variables externes influençant <span class="math inline">\(y\)</span>, qui sont elles-mêmes corrélées dans l’espace.</p>
<p>Par exemple, supposons que l’abondance d’une espèce soit corrélée entre deux sites rapprochés:</p>
<ul>
<li><p>cette dépendance spatiale peut être induite si elle est due à une corrélation spatiale des facteurs d’habitat qui favorisent ou défavorisent l’espèce;</p></li>
<li><p>ou elle peut être intrinsèque si elle est due à la dispersion d’individus entre sites rapprochés.</p></li>
</ul>
<p>Dans plusieurs cas, les deux types de dépendance affectent une variable donnée.</p>
<p>Si la dépendance est simplement induite et que les variables externes qui en sont la cause sont incluses dans le modèle expliquant <span class="math inline">\(y\)</span>, alors les résidus du modèle seront indépendants et nous pouvons utiliser toutes les méthodes déjà vues qui ignorent la dépendance spatiale.</p>
<p>Cependant, si la dépendance est intrinsèque ou due à des influences externes non-mesurées, alors il faudra tenir compte de la dépendance spatiale des résidus dans le modèle.</p>
</div>
<div id="différentes-façons-de-modéliser-les-effets-spatiaux" class="section level2">
<h2>Différentes façons de modéliser les effets spatiaux</h2>
<p>Dans cette formation, nous modéliserons directement les corrélations spatiales de nos données. Il est utile de comparer cette approche à d’autres façons d’inclure des aspects spatiaux dans un modèle statistique.</p>
<p>D’abord, nous pourrions inclure des prédicteurs dans le modèle qui représentent la position (ex.: longitude, latitude). De tels prédicteurs peuvent être utiles pour détecter une tendance ou un gradient systématique à grande échelle, que cette tendance soit linéaire ou non (par exemple, avec un modèle additif généralisé).</p>
<p>En contraste à cette approche, les modèles que nous verrons maintenant servent à modéliser une corrélation spatiale dans les fluctuations aléatoires d’une variable (i.e., dans les résidus après avoir enlevé tout effet systématique).</p>
<p>Les modèles mixtes utilisent des effets aléatoires pour représenter la non-indépendance de données sur la base de leur groupement, c’est-à-dire qu’après avoir tenu compte des effets fixes systématiques, les données d’un même groupe sont plus semblables (leur variation résiduelle est corrélée) par rapport aux données de groupes différents. Ces groupes étaient parfois définis selon des critères spatiaux (observations regroupées en sites).</p>
<p>Cependant, dans un contexte d’effet aléatoire de groupe, tous les groupes sont aussi différents les uns des autres, ex.: deux sites à 100 km l’un de l’autre ne sont pas plus ou moins semblables que deux sites distants de 2 km.</p>
<p>Les méthodes que nous verrons ici et dans les prochains parties de la formation nous permettent donc ce modéliser la non-indépendance sur une échelle continue (plus proche = plus corrélé) plutôt que seulement discrète (hiérarchie de groupements).</p>
</div>
</div>
<div id="modèles-géostatistiques" class="section level1">
<h1>Modèles géostatistiques</h1>
<p>La géostatistique désigne un groupe de techniques tirant leur origine en sciences de la Terre. Elle s’intéresse à des variables distribuées de façon continue dans l’espace, dont on cherche à estimer la distribution en échantillonnant un nombre de points. Un exemple classique de ces techniques provient du domaine minier, où l’on cherchait à créer une carte de la concentration du minerai sur un site à partir d’échantillons pris à différents points du site.</p>
<p>Pour ces modèles, nous supposerons que <span class="math inline">\(z(x, y)\)</span> est une variable spatiale stationnaire mesurée selon les coordonnées <span class="math inline">\(x\)</span> et <span class="math inline">\(y\)</span>.</p>
<div id="variogramme" class="section level2">
<h2>Variogramme</h2>
<p>Un aspect central de la géostatistique est l’estimation du variogramme <span class="math inline">\(\gamma_z\)</span> de la variable <span class="math inline">\(z\)</span>. Le variogramme est égal à la moitié de l’écart carré moyen entre les valeurs de <span class="math inline">\(z\)</span> pour deux points <span class="math inline">\((x_i, y_i)\)</span> et <span class="math inline">\((x_j, y_j)\)</span> séparés par une distance <span class="math inline">\(h\)</span>.</p>
<p><span class="math display">\[\gamma_z(h) = \frac{1}{2} \text{E} \left[ \left( z(x_i, y_i) - z(x_j, y_j) \right)^2 \right]_{d_{ij} = h}\]</span></p>
<p>Dans cette équation, la fonction <span class="math inline">\(\text{E}\)</span> avec l’indice <span class="math inline">\(d_{ij}=h\)</span> désigne l’espérance statistique (autrement dit, la moyenne) de l’écart au carré entre les valeurs de <span class="math inline">\(z\)</span> pour les points séparés par une distance <span class="math inline">\(h\)</span>.</p>
<p>Si on préfère exprimer l’autocorrélation <span class="math inline">\(\rho_z(h)\)</span> entre mesures de <span class="math inline">\(z\)</span> séparées par une distance <span class="math inline">\(h\)</span>, celle-ci est reliée au variogramme par l’équation:</p>
<p><span class="math display">\[\gamma_z = \sigma_z^2(1 - \rho_z)\]</span> ,</p>
<p>où <span class="math inline">\(\sigma_z^2\)</span> est la variance globale de <span class="math inline">\(z\)</span>.</p>
<p>Notez que <span class="math inline">\(\gamma_z = \sigma_z^2\)</span> si nous sommes à une distance où les mesures de <span class="math inline">\(z\)</span> sont indépendantes, donc <span class="math inline">\(\rho_z = 0\)</span>. Dans ce cas, on voit bien que <span class="math inline">\(\gamma_z\)</span> s’apparente à une variance, même s’il est parfois appelé “semivariogramme” ou “semivariance” en raison du facteur 1/2 dans l’équation ci-dessus.</p>
</div>
<div id="modèles-théoriques-du-variogramme" class="section level2">
<h2>Modèles théoriques du variogramme</h2>
<p>Plusieurs modèles paramétriques ont été proposés pour représenter la corrélation spatiale en fonction de la distance entre points d’échantillonnage. Considérons d’abord une corrélation qui diminue de façon exponentielle:</p>
<p><span class="math display">\[\rho_z(h) = e^{-h/r}\]</span></p>
<p>Ici, <span class="math inline">\(\rho_z = 1\)</span> pour <span class="math inline">\(h = 0\)</span> et la corréaltion est multipliée par <span class="math inline">\(1/e \approx 0.37\)</span> pour chaque augmentation de <span class="math inline">\(r\)</span> de la distance. Dans ce contexte, <span class="math inline">\(r\)</span> se nomme la portée (<em>range</em>) de la corrélation.</p>
<p>À partir de l’équation ci-dessus, nous pouvons calculer le variogramme correspondant.</p>
<p><span class="math display">\[\gamma_z(h) = \sigma_z^2 (1 - e^{-h/r})\]</span></p>
<p>Voici une représentation graphique de ce variogramme.</p>
<p><img src="2-Modeles_geostatistiques_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>En raison de la fonction exponentielle, la valeur de <span class="math inline">\(\gamma\)</span> à des grandes distances s’approche de la variance globale <span class="math inline">\(\sigma_z^2\)</span> sans exactement l’atteindre. Cette asymptote est appelée palier (<em>sill</em>) dans le contexte géostatistique et représentée par le symbole <span class="math inline">\(s\)</span>.</p>
<p>Finalement, il n’est parfois pas réaliste de supposer une corrélation parfaite lorsque la distance tend vers 0, en raison d’une variation possible de <span class="math inline">\(z\)</span> à très petite échelle. On peut ajouter au modèle un effet de pépite (<em>nugget</em>), noté <span class="math inline">\(n\)</span>, pour que <span class="math inline">\(\gamma\)</span> s’approche de <span class="math inline">\(n\)</span> (plutôt que 0) si <span class="math inline">\(h\)</span> tend vers 0. Le terme pépite provient de l’origine minière de ces techniques, où une pépite d’un minerai pourrait être la source d’une variation abrupte de la concentration à petite échelle.</p>
<p>En ajoutant l’effet de pépite, le reste du variogramme est “compressé” pour conserver le même palier, ce qui résulte en l’équation suivante.</p>
<p><span class="math display">\[\gamma_z(h) = n + (s - n) (1 - e^{-h/r})\]</span></p>
<p>Dans le package <em>gstat</em> que nous utiliserons ci-dessous, le terme <span class="math inline">\((s - n)\)</span> est le palier partiel (<em>partial sill</em>, ou <code>psill</code>) pour la partie exponentielle.</p>
<p><img src="2-Modeles_geostatistiques_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>En plus du modèle exponentiel, deux autres modèles théoriques courants pour le variogramme sont le modèle gaussien (où la corrélation suit une courbe demi-normale), ainsi que le modèle sphérique (où le variogramme augmente de façon linéaire au départ pour ensuite courber et atteindre le palier à une distance égale à sa portée <span class="math inline">\(r\)</span>). Le modèle sphérique permet donc à la corrélation d’être exactement 0 à grande distance, plutôt que de s’approcher graduellement de zéro dans le cas des autres modèles.</p>
<table>
<colgroup>
<col width="22%" />
<col width="35%" />
<col width="41%" />
</colgroup>
<thead>
<tr class="header">
<th>Modèle</th>
<th><span class="math inline">\(\rho(h)\)</span></th>
<th><span class="math inline">\(\gamma(h)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Exponentiel</td>
<td><span class="math inline">\(\exp\left(-\frac{h}{r}\right)\)</span></td>
<td><span class="math inline">\(s \left(1 - \exp\left(-\frac{h}{r}\right)\right)\)</span></td>
</tr>
<tr class="even">
<td>Gaussien</td>
<td><span class="math inline">\(\exp\left(-\frac{h^2}{r^2}\right)\)</span></td>
<td><span class="math inline">\(s \left(1 - \exp\left(-\frac{h^2}{r^2}\right)\right)\)</span></td>
</tr>
<tr class="odd">
<td>Sphérique <span class="math inline">\((h &lt; r)\)</span> *</td>
<td><span class="math inline">\(1 - \frac{3}{2}\frac{h}{r} + \frac{1}{2}\frac{h^3}{r^3}\)</span></td>
<td><span class="math inline">\(s \left(\frac{3}{2}\frac{h}{r} - \frac{1}{2}\frac{h^3}{r^3} \right)\)</span></td>
</tr>
</tbody>
</table>
<p>* Pour le modèle sphérique, <span class="math inline">\(\rho = 0\)</span> et <span class="math inline">\(\gamma = s\)</span> si <span class="math inline">\(h \ge r\)</span>.</p>
<p><img src="2-Modeles_geostatistiques_files/figure-html/unnamed-chunk-3-1.png" width="864" /></p>
</div>
<div id="variogramme-empirique" class="section level2">
<h2>Variogramme empirique</h2>
<p>Pour estimer <span class="math inline">\(\gamma_z(h)\)</span> à partir de données empiriques, nous devons définir des classes de distance, donc grouper différentes distances dans une marge <span class="math inline">\(\pm \delta\)</span> autour d’une distance <span class="math inline">\(h\)</span>, puis calculer l’écart-carré moyen pour les paires de points dans cette classe de distance.</p>
<p><span class="math display">\[\hat{\gamma_z}(h) = \frac{1}{2 N_{\text{paires}}} \sum \left[ \left( z(x_i, y_i) - z(x_j, y_j) \right)^2 \right]_{d_{ij} = h \pm \delta}\]</span></p>
<p>Nous verrons dans la partie suivante comment estimer un variogramme dans R.</p>
</div>
<div id="modèle-de-régression-avec-corrélation-spatiale" class="section level2">
<h2>Modèle de régression avec corrélation spatiale</h2>
<p>L’équation suivante représente une régression linéaire multiple incluant une corrélation spatiale résiduelle:</p>
<p><span class="math display">\[v = \beta_0 + \sum_i \beta_i u_i + z + \epsilon\]</span></p>
<p>Ici, <span class="math inline">\(v\)</span> désigne la variable réponse et <span class="math inline">\(u\)</span> les prédicteurs, pour ne pas confondre avec les coordonnées spatiales <span class="math inline">\(x\)</span> et <span class="math inline">\(y\)</span>.</p>
<p>En plus du résidu <span class="math inline">\(\epsilon\)</span> qui est indépendant entre les observations, le modèle inclut un terme <span class="math inline">\(z\)</span> qui représente la portion spatialement corrélée de la variance résiduelle.</p>
<p>Voici une suggestions d’étapes à suivre pour appliquer ce type de modèle:</p>
<ol style="list-style-type: decimal">
<li><p>Ajuster le modèle de régression sans corrélation spatiale.</p></li>
<li><p>Vérifier la présence de corrélation spatiale à partir du variogramme empirique des résidus.</p></li>
<li><p>Ajuster un ou plusieurs modèles de régression avec corrélation spatiale et choisir celui qui montre le meilleur ajustement aux données.</p></li>
</ol>
</div>
</div>
<div id="modèles-géostatistiques-dans-r" class="section level1">
<h1>Modèles géostatistiques dans R</h1>
<p>Le package <em>gstat</em> contient des fonctions liées à la géostatistique. Pour cet exemple, nous utiliserons le jeu de données <code>oxford</code> de ce package, qui contient des mesures de propriétés physiques et chimiques pour 126 échantillons du sol d’un site, ainsi que leurs coordonnées <code>XCOORD</code> et <code>YCOORD</code>.</p>
<pre class="r"><code>library(gstat)

data(oxford)
str(oxford)</code></pre>
<pre><code>## &#39;data.frame&#39;:    126 obs. of  22 variables:
##  $ PROFILE  : num  1 2 3 4 5 6 7 8 9 10 ...
##  $ XCOORD   : num  100 100 100 100 100 100 100 100 100 100 ...
##  $ YCOORD   : num  2100 2000 1900 1800 1700 1600 1500 1400 1300 1200 ...
##  $ ELEV     : num  598 597 610 615 610 595 580 590 598 588 ...
##  $ PROFCLASS: Factor w/ 3 levels &quot;Cr&quot;,&quot;Ct&quot;,&quot;Ia&quot;: 2 2 2 3 3 2 3 2 3 3 ...
##  $ MAPCLASS : Factor w/ 3 levels &quot;Cr&quot;,&quot;Ct&quot;,&quot;Ia&quot;: 2 3 3 3 3 2 2 3 3 3 ...
##  $ VAL1     : num  3 3 4 4 3 3 4 4 4 3 ...
##  $ CHR1     : num  3 3 3 3 3 2 2 3 3 3 ...
##  $ LIME1    : num  4 4 4 4 4 0 2 1 0 4 ...
##  $ VAL2     : num  4 4 5 8 8 4 8 4 8 8 ...
##  $ CHR2     : num  4 4 4 2 2 4 2 4 2 2 ...
##  $ LIME2    : num  4 4 4 5 5 4 5 4 5 5 ...
##  $ DEPTHCM  : num  61 91 46 20 20 91 30 61 38 25 ...
##  $ DEP2LIME : num  20 20 20 20 20 20 20 20 40 20 ...
##  $ PCLAY1   : num  15 25 20 20 18 25 25 35 35 12 ...
##  $ PCLAY2   : num  10 10 20 10 10 20 10 20 10 10 ...
##  $ MG1      : num  63 58 55 60 88 168 99 59 233 87 ...
##  $ OM1      : num  5.7 5.6 5.8 6.2 8.4 6.4 7.1 3.8 5 9.2 ...
##  $ CEC1     : num  20 22 17 23 27 27 21 14 27 20 ...
##  $ PH1      : num  7.7 7.7 7.5 7.6 7.6 7 7.5 7.6 6.6 7.5 ...
##  $ PHOS1    : num  13 9.2 10.5 8.8 13 9.3 10 9 15 12.6 ...
##  $ POT1     : num  196 157 115 172 238 164 312 184 123 282 ...</code></pre>
<p>Supposons que nous souhaitons modéliser la concentration de magnésium (<code>MG1</code>), représentée en fonction de la position spatiale dans le graphique suivant.</p>
<pre class="r"><code>library(ggplot2)
ggplot(oxford, aes(x = YCOORD, y = XCOORD, size = MG1)) +
    geom_point() +
    coord_fixed()</code></pre>
<p><img src="2-Modeles_geostatistiques_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Notez que les axes <span class="math inline">\(x\)</span> et <span class="math inline">\(y\)</span> ont été inversés par souci d’espace. La fonction <code>coord_fixed()</code> de <em>ggplot2</em> assure que l’échelle soit la même sur les deux axes, ce qui est utile pour représenter des données spatiales.</p>
<p>Nous voyons tout de suite que ces mesures ont été prises sur une grille de 100 m de côté. Il semble que la concentration de magnésium soit spatialement corrélée, bien qu’il puisse s’agir d’une corrélation induite par une autre variable. Nous savons notamment que la concentration de magnésium est reliée négativement au pH du sol (<code>PH1</code>).</p>
<pre class="r"><code>ggplot(oxford, aes(x = PH1, y = MG1)) +
    geom_point()</code></pre>
<p><img src="2-Modeles_geostatistiques_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>La fonction <code>variogram</code> de <em>gstat</em> sert à estimer un variogramme à partir de données empiriques. Voici le résultat obtenu pour la variable <code>MG1</code>.</p>
<pre class="r"><code>var_mg &lt;- variogram(MG1 ~ 1, locations = ~ XCOORD + YCOORD, data = oxford)
var_mg</code></pre>
<pre><code>##     np     dist    gamma dir.hor dir.ver   id
## 1  225 100.0000 1601.404       0       0 var1
## 2  200 141.4214 1950.805       0       0 var1
## 3  548 215.0773 2171.231       0       0 var1
## 4  623 303.6283 2422.245       0       0 var1
## 5  258 360.5551 2704.366       0       0 var1
## 6  144 400.0000 2948.774       0       0 var1
## 7  570 427.5569 2994.621       0       0 var1
## 8  291 500.0000 3402.058       0       0 var1
## 9  366 522.8801 3844.165       0       0 var1
## 10 200 577.1759 3603.060       0       0 var1
## 11 458 619.8400 3816.595       0       0 var1
## 12  90 670.8204 3345.739       0       0 var1</code></pre>
<p>La formule <code>MG1 ~ 1</code> indique qu’aucun prédicteur linéaire n’est inclus dans ce modèle, tandis que l’argument <code>locations</code> indique quelles variables du tableau correspondent aux coordonnées spatiales.</p>
<p>Dans le tableau obtenu, <code>gamma</code> est la valeur du variogramme pour la classe de distance centrée sur <code>dist</code>, tandis que <code>np</code> est le nombre de paires de points dans cette classe. Ici, puisque les points sont situés sur une grille, nous obtenons des classes de distance régulières (ex.: 100 m pour les points voisins sur la grille, 141 m pour les voisins en diagonale, etc.).</p>
<p>Nous nous limitons ici à l’estimation de variogrammes isotropiques, c’est-à-dire que le variogramme dépend seulement de la distance entre les deux points et non de la direction. Bien que nous n’ayons pas le temps de le voir aujourd’hui, il est possible avec <em>gstat</em> d’estimer séparément le variogramme dans différentes directions.</p>
<p>Nous pouvons illustrer le variogramme avec <code>plot</code>.</p>
<pre class="r"><code>plot(var_mg, col = &quot;black&quot;)</code></pre>
<p><img src="2-Modeles_geostatistiques_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Si nous voulons estimer la corrélation spatiale résiduelle de <code>MG1</code> après avoir inclus l’effet de <code>PH1</code>, nous pouvons ajouter ce prédicteur à la formule.</p>
<pre class="r"><code>var_mg &lt;- variogram(MG1 ~ PH1, locations = ~ XCOORD + YCOORD, data = oxford)
plot(var_mg, col = &quot;black&quot;)</code></pre>
<p><img src="2-Modeles_geostatistiques_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>En incluant l’effet du pH, la portée de la corrélation spatiale semble diminuer, alors que le plateau est atteint autour de 300 m. Il semble même que le variogramme diminue au-delà de 400 m. En général, nous supposons que la variance entre deux points ne diminue pas avec la distance, à moins d’avoir un patron spatial périodique.</p>
<p>La fonction <code>fit.variogram</code> accepte comme arguments un variogramme estimé à partir des données, ainsi qu’un modèle théorique décrit dans une fonction <code>vgm</code>, puis estime les paramètres de ce modèle en fonction des données. L’ajustement se fait par la méthode des moindres carrés.</p>
<p>Par exemple, <code>vgm("Exp")</code> indique d’ajuster un modèle exponentiel.</p>
<pre class="r"><code>vfit &lt;- fit.variogram(var_mg, vgm(&quot;Exp&quot;))
vfit</code></pre>
<pre><code>##   model    psill    range
## 1   Nug    0.000  0.00000
## 2   Exp 1951.496 95.11235</code></pre>
<p>Il n’y a aucun effet de pépite, car <code>psill = 0</code> pour la partie <code>Nug</code> (<em>nugget</em>) du modèle. La partie exponentielle a un palier à 1951 et une portée de 95 m.</p>
<p>Pour comparer différents modèles, on peut donner un vecteur de noms de modèles à <code>vgm</code>. Dans l’exemple suivant, nous incluons les modèles exponentiel, gaussien (“Gau”) et sphérique (“Sph”).</p>
<pre class="r"><code>vfit &lt;- fit.variogram(var_mg, vgm(c(&quot;Exp&quot;, &quot;Gau&quot;, &quot;Sph&quot;)))
vfit</code></pre>
<pre><code>##   model    psill    range
## 1   Nug    0.000  0.00000
## 2   Exp 1951.496 95.11235</code></pre>
<p>La fonction nous donne le résultat du modèle le mieux ajusté (plus faible somme des écarts au carré), qui est ici le même modèle exponentiel.</p>
<p>Finalement, nous pouvons superposer le modèle théorique et le variogramme empirique sur un même graphique.</p>
<pre class="r"><code>plot(var_mg, vfit, col = &quot;black&quot;)</code></pre>
<p><img src="2-Modeles_geostatistiques_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<div id="régression-avec-corrélation-spatiale" class="section level2">
<h2>Régression avec corrélation spatiale</h2>
<p>Nous avons vu ci-dessus que le package <em>gstat</em> permet d’estimer le variogramme des résidus d’un modèle linéaire. Dans notre exemple, la concentration de magnésium était modélisée en fonction du pH, avec des résidus spatialement corrélés.</p>
<p>Un autre outil pour ajuster ce même type de modèle est la fonction <code>gls</code> du package <em>nlme</em>, qui est inclus avec l’installation de R.</p>
<p>Cette fonction applique la méthode des moindres carrés généralisés (<em>generalized least squares</em>) pour ajuster des modèles de régression linéaire lorsque les résidus ne sont pas indépendants ou lorsque la variance résiduelle n’est pas la même pour toutes les observations. Comme les estimés des coefficients dépendent de l’estimé des corrélations entre les résidus et que ces derniers dépendent eux-mêmes des coefficients, le modèle est ajusté par un algorithme itératif:</p>
<ol style="list-style-type: decimal">
<li><p>On ajuste un modèle de régression linéaire classique (sans corrélation) pour obtenir des résidus.</p></li>
<li><p>On ajuste le modèle de corrélation spatiale (variogramme) avec ses résidus.</p></li>
<li><p>On ré-estime les coefficients de la régression en tenant compte maintenant des corrélations.</p></li>
</ol>
<p>Les étapes 2 et 3 sont répétées jusqu’à ce que les estimés soient stables à une précision voulue.</p>
<p>Voici l’application de cette méthode au même modèle pour la concentration de magnésium dans le jeu de données <code>oxford</code>. Dans l’argument <code>correlation</code> de <code>gls</code>, nous spécifions un modèle de corrélation exponentielle en fonction de nos coordonnées spatiales et indiquons que nous voulons aussi estimer un effet de pépite.</p>
<p>En plus de la corrélation exponentielle <code>corExp</code>, la fonction <code>gls</code> peut aussi estimer un modèle gaussien (<code>corGaus</code>) ou sphérique (<code>corSpher</code>).</p>
<pre class="r"><code>library(nlme)
gls_mg &lt;- gls(MG1 ~ PH1, oxford, 
              correlation = corExp(form = ~ XCOORD + YCOORD, nugget = TRUE))
summary(gls_mg)</code></pre>
<pre><code>## Generalized least squares fit by REML
##   Model: MG1 ~ PH1 
##   Data: oxford 
##       AIC      BIC   logLik
##   1278.65 1292.751 -634.325
## 
## Correlation Structure: Exponential spatial correlation
##  Formula: ~XCOORD + YCOORD 
##  Parameter estimate(s):
##       range      nugget 
## 478.0322964   0.2944753 
## 
## Coefficients:
##                Value Std.Error   t-value p-value
## (Intercept) 391.1387  50.42343  7.757084       0
## PH1         -41.0836   6.15662 -6.673079       0
## 
##  Correlation: 
##     (Intr)
## PH1 -0.891
## 
## Standardized residuals:
##        Min         Q1        Med         Q3        Max 
## -2.1846957 -0.6684520 -0.3687813  0.4627580  3.1918604 
## 
## Residual standard error: 53.8233 
## Degrees of freedom: 126 total; 124 residual</code></pre>
<p>Pour comparer ce résultat au variogramme ajusté ci-dessus, il faut transformer les paramètres donnés par <code>gls</code>. La portée (range) a le même sens dans les deux cas et correspond à 478 m pour le résultat de <code>gls</code>. La variance globale des résidus est le carré de <code>Residual standard error</code>. L’effet de pépite ici (0.294) est exprimé comme fraction de cette variance. Finalement, pour obtenir le palier partiel de la partie exponentielle, il faut soustraire l’effet de pépite de la variance totale.</p>
<p>Après avoir réalisé ces calculs, nous pouvons donner ces paramètres à la fonction <code>vgm</code> de <em>gstat</em> pour superposer ce variogramme estimé par <code>gls</code> à notre variogramme des résidus du modèle linéaire classique.</p>
<pre class="r"><code>gls_range &lt;- 478
gls_var &lt;- 53.823^2
gls_nugget &lt;- 0.294 * gls_var
gls_psill &lt;- gls_var - gls_nugget

plot(var_mg, vgm(&quot;Exp&quot;, psill = gls_psill, range = gls_range, nugget = gls_nugget),
     col = &quot;black&quot;, ylim = c(0, 4000))</code></pre>
<p><img src="2-Modeles_geostatistiques_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Est-ce que le modèle est moins bien ajusté aux données ici? En fait, ce variogramme empirique représenté par les points avait été obtenu à partir des résidus du modèle linéaire ignorant la corrélation spatiale, donc c’est un estimé biaisé des corrélations spatiales réelles. La méthode est quand même adéquate pour vérifier rapidement s’il y a présence de corrélations spatiales. Toutefois, pour ajuster simultanément les coefficients de la régression et les paramètres de corrélation spatiale, l’approche des moindres carrés généralisés (GLS) est préférable et produira des estimés plus justes.</p>
<p>Finalement, notez que le résultat du modèle <code>gls</code> donne aussi l’AIC, que nous pouvons utiliser pour comparer l’ajustement de différents modèles (avec différents prédicteurs ou différentes formes de corrélation spatiale).</p>
</div>
<div id="exercice" class="section level2">
<h2>Exercice</h2>
<p>Le fichier <a href="data/bryo_belg.csv">bryo_belg.csv</a> est adapté des données de l’étude:</p>
<blockquote>
<p>Neyens, T., Diggle, P.J., Faes, C., Beenaerts, N., Artois, T. et Giorgi, E. (2019) Mapping species richness using opportunistic samples: a case study on ground-floor bryophyte species richness in the Belgian province of Limburg. <em>Scientific Reports</em> 9, 19122. <a href="https://doi.org/10.1038/s41598-019-55593-x" class="uri">https://doi.org/10.1038/s41598-019-55593-x</a></p>
</blockquote>
<p>Ce tableau de données indique la richesse spécifique des bryophytes au sol (<em>richness</em>) pour différents points d’échantillonnage de la province belge de Limbourg, avec leur position <em>(x, y)</em> en km, en plus de l’information sur la proportion de forêts (<em>forest</em>) et de milieux humides (<em>wetland</em>) dans une cellule de 1 km<span class="math inline">\(^2\)</span> contenant le point d’échantillonnage.</p>
<pre class="r"><code>bryo_belg &lt;- read.csv(&quot;data/bryo_belg.csv&quot;)
head(bryo_belg)</code></pre>
<pre><code>##   richness    forest   wetland        x        y
## 1        9 0.2556721 0.5036614 228.9516 220.8869
## 2        6 0.6449114 0.1172068 227.6714 219.8613
## 3        5 0.5039905 0.6327003 228.8252 220.1073
## 4        3 0.5987329 0.2432942 229.2775 218.9035
## 5        2 0.7600775 0.1163538 209.2435 215.2414
## 6       10 0.6865434 0.0000000 210.4142 216.5579</code></pre>
<p>Pour cet exercice, nous utiliserons la racine carrée de la richesse spécifique comme variable réponse. La transformation racine carrée permet souvent d’homogénéiser la variance des données de comptage afin d’y appliquer une régression linéaire.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Ajustez un modèle linéaire de la richesse spécifique transformée en fonction de la fraction de forêt et de milieux humides, sans tenir compte des corrélations spatiales. Quel est l’effet des deux prédicteurs selon ce modèle?</p></li>
<li><p>Calculez le variogramme empirique des résidus du modèle en (a). Semble-t-il y avoir une corrélation spatiale entre les points?</p></li>
</ol>
<p><em>Note</em>: L’argument <code>cutoff</code> de la fonction <code>variogram</code> spécifie la distance maximale à laquelle le variogramme est calculé. Vous pouvez ajuster manuellement cette valeur pour bien voir le palier.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li><p>Ré-ajustez le modèle linéaire en (a) avec la fonction <code>gls</code> du package <em>nlme</em>, en essayant différents types de corrélations spatiales (exponentielle, gaussienne, sphérique). Comparez les modèles (incluant celui sans corrélation spatiale) avec l’AIC.</p></li>
<li><p>Quel est l’effet de la fraction de forêts et de milieux humides selon le modèle en (c)? Expliquez les différences entre les conclusions de ce modèle et du modèle en (a).</p></li>
</ol>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
